# ==============================================================================
#    NAME: scripts/0_common.R
#   INPUT: None
# ACTIONS: Set common settings used across the scripts
#  OUTPUT: Set of global variables loaded into R's environment
# RUNTIME: N/A
#  AUTHOR: Thomas D. Pellegrin <thomas@pellegr.in>
#    YEAR: 2023
# ==============================================================================

# ==============================================================================
# 0 Directory locations
# ==============================================================================

dir <- list(
  "cal"    = "data/cal",           # Calibrated takeoff performance data
  "cli"    = "data/cli",           # Climate data in NetCDF format
  "log"    = "logs",               # Log files
  "plt"    = "plots",              # Plots generated by R
  "res"    = "data/res",           # Results
  "imp_pq" = "data/imp_parquet",   # Imported climate obs (one file per NetCDF)
  "cli_pq" = "data/cli_parquet",   # Transformed climate (one file per airport)
  "tko_pq" = "data/tko_parquet"    # Takeoff outcomes (one file per airport)
)

# ==============================================================================
# 1 File locations
# ==============================================================================

fls <- list(
  "act" = "data/act/aircraft.csv",     # Aircraft data from Sun et al. (2020)
  "net" = "data/cli/netcdf.csv",       # List of NetCDF files from the ESGF
  "geo" = "data/pop/geolocation.csv",  # Airport coordinates from OurAirports.com
  "rwy" = "data/pop/runways.csv",      # Runways and TODA from Lufthansa Systems
  "tra" = "data/pop/traffic.csv",      # 2019 traffic by airport from IATA
  "pop" = "data/pop/population.parquet" # Population & sample airports (1_pop -> ...)
)

# ==============================================================================
# 2 Aircraft types
# ==============================================================================

act <- list(
  "Airbus A320neo"   = "A20n", # With LEAP-1A29 engines
  "Airbus A350-900"  = "A359", # With Trent XWB-84 engines
  "Boeing 737 MAX 9" = "B39m", # With CFM LEAP-1B27 engines
  "Boeing 787-9"     = "B789"  # With Trent 1000-K2 engines
)

bod <- list(
  "Narrowbody" = c("A20n", "B39m"),
  "Widebody"   = c("A359", "B789")
)

# ==============================================================================
# 3 Climate simulation parameters
# ==============================================================================

# Climatic variables and plot units
cli <- list(
  "tas"  = "in °C",   # Near-surface air temperature
  "ps"   = "in hPa",  # Near-surface air pressure
  "huss" = "in g/kg", # Near-surface specific humidity
  "rho"  = "in g/m³", # Near-surface air density
  "hdw"  = "in m/s"   # Near-surface headwind
)

# Latitudinal boundaries of the Earth's climate zones
geo <- list(
  "Frigid"    = c(-90L,     -66.5635), # Antarctic zone
  "Temperate" = c(-66.5635, -23.4365), # South temperate zone
  "Tropical"  = c(-23.4365,  23.4365), # Tropical zone
  "Temperate" = c( 23.4365,  66.5635), # North temperate zone
  "Frigid"    = c( 66.5635,  90L)      # Arctic zone
)

# ==============================================================================
# 4 Takeoff simulation parameters
# ==============================================================================

sim <- list(
  # Calibration settings
  "clb_ang"     = 7.7,         # Average climb angle to screen height
  "flp_ang"     = 10L,         # Takeoff flap deflection angle in degrees
  "max_lof"     = 1.2,         # Ratio from CLmax to CLlof (Roskam, 2018, p 95)
  "opt_cls"     = c(1.6, 2.2), # Range of cL inputs passed to the optimizer
  "opt_tol"     = 10^-3,       # Optimizer tolerance
  "rwy_frc"     = .02,         # Friction coefficient for dry concrete/asphalt
  "rwy_slp"     = 0L,          # Runway slope in °
  "scr_hgt"     = 35L,         # Minimum screen height above terrain
  "thr_rto"     = 0L,          # Thrust reduction used for calibration
  "tod_mul"     = 1.15,        # Regulatory takeoff distance multiplier
  # Model settings
  "int_stp"     = 10L,         # Integration steps (model resolution)
  "lf_belf"     = .67,         # Break-even load factor
  "pax_avg"     = 87L,         # Mean adult pax weight (Filippone, 2012, p. 52)
  "pop_thr"     = 10^6,        # Minimum passenger traffic for airport sample
  "thr_inc"     = 1L,          # Thrust increase at each iteration in % point
  "thr_ini"     = 25L,         # Thrust reduction for simulation in %
  # Natural constants
  "adb_idx"     = 1.4,         # Adiabatic index for dry air at ISA temperature
  "ft_to_m"     = .3048,       # Number of m in one ft
  "g"           = 9.806665,    # Gravitational acceleration constant in m/s²
  "isa_hdw"     = 0L,          # ISA near-surface headwind in m/s
  "isa_ps"      = 101325L,     # ISA sea-level air pressure in Pa
  "isa_rho"     = 1.225,       # ISA sea-level air density in kg/m³
  "isa_tas"     = 288.15,      # ISA sea-level air temperature in K
  "k_to_c"      = 273.15,      # Number of °K in 0 °C
  "rsp_air"     = 287.058,     # Specific gas constant for dry air in J/(kg·K)
  "rsp_h2o"     = 461.495,     # Spec. gas constant for water vapor in J/(kg·K)
  # ISA tropospheric lapse rate in K/m (used by flat-rating and ps correction)
  "isa_lap"  = .0065,

  # Engine flat-rating (thrust-temperature lapse) [REV. 2026]
  # Corner temperature is local ISA + flat_dev; thrust decays above it.
  # flat_exp = 2.5 gives ~0.8%/K above the corner (representative high-bypass).
  "flat_dev"  = 15L,
  "flat_exp"  = 2.5,

  # Numerical / feasibility settings [REV. 2026]
  # acc_eps: minimum ground-roll acceleration (m/s²) for a takeoff to be feasible
  # todr_cap: TODR (m) above which a finite takeoff is treated as field-infeasible
  "acc_eps"   = 1e-3,
  "todr_cap"  = 6000L,

  # Molar-mass ratio of water vapour to dry air (used by huss density path)
  "mwr"       = 0.62198,
  # Analysis settings
  "quantiles"   = seq(from = 0L, to = 1L, by = .25) # For boxplot analysis
)

# ==============================================================================
# 5 Plotting parameters
# ==============================================================================

plt <- list(
  # Font size
  "axis.text"    = 5L,
  "axis.title"   = 6L,
  "label.text"   = 2L,
  "legend.title" = 5L,
  "legend.text"  = 5L,
  "strip.text"   = 5L,
  "text"         = 9L,
  # File
  "device"       = "png",
  "path"         = dir$plt,
  # Canvas
  "dpi"          = "retina",
  "scale"        = 1L,
  "height"       = 5.2,
  "width"        = 9L,
  "units"        = "in"
)

# ==============================================================================
# 6 Common functions
# ==============================================================================

# ==============================================================================
# 6.1 Function to distribute a computational task across cores. Parameters:
# crs = number of cores to use in the cluster
# lib = libraries required by each core
# lst = list to be distributed across cores
# fun = function to be applied to each list item
# ==============================================================================

fn_par_lapply <- function(crs, pkg, lst, fun) {

  # Set the log file to the name of the function being passed
  log <- paste(dir$log, "/", substitute(fun), ".log", sep = "")

  # Clear the log file in case it is not empty
  close(file(description = log, open = "w"))

  # Build the cluster of workers
  cl <- parallel::makeCluster(spec = crs, outfile = log)

  # Have each worker load the required packages
  parallel::clusterCall(
    cl  = cl,
    fun = function() {
      suppressMessages(lapply(X = pkg, FUN = require, character.only = TRUE))
    }
  )

  # Pass all global variables to each worker
  parallel::clusterExport(cl = cl, varlist = ls(.GlobalEnv))

  # Distribute the task across the workers
  parallel::parLapply(cl = cl, X = lst, fun = fun)

  # Shut down the workers
  parallel::stopCluster(cl = cl)

}

# ==============================================================================
# 6.2 Function to print a timestamped worker log line. Parameters:
# ... = message tokens (typically a context label such as the airport ICAO
#       followed by the message), joined to the timestamp + PID prefix with
#       single spaces
# ==============================================================================

fn_log <- function(...) {

  # Prefix every line with the timestamp and the zero-padded worker PID
  print(
    paste(
      Sys.time(),
      "pid",
      stringr::str_pad(
        Sys.getpid(),
        width = 5L,
        side  = "left",
        pad   = " "
      ),
      ...,
      sep = " "
    )
  )

}

# EOF
